### ISSUE TITLE
Change google search result title

### ISSUE THREAD

**Issue by NielsHokke** [ZED-IoT/ZED-IoT.github.io#7]
Er staat nu alleen ZED, als het mogelijk is dit graag verranderen naar: "ZED: developing batteryless and wireless solutions"

![Zed_search_result](https://user-images.githubusercontent.com/17768955/106895224-42924b00-66f0-11eb-92d8-8fd2c10df6d5.JPG)

**Comment by MKraijenoord** [comment]
I have updated the title
